name: shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  line_icons: ^2.0.2
  buttons_tabbar: ^1.3.13
  carousel_slider: ^4.0.0
  provider: ^6.1.2
  http: ^1.2.2
  get: ^4.6.6
  fluttertoast: ^8.2.8
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/images/
  
